name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: PWD
      run: ls
    - name: Make project
      run: make
    - name: Run executable
      run: ./hello_world
    - name: Clean project
      run: make clean
