name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Make binary
      run: make
    - name: Run executable
      run: ./hello_world
    - name: Clean directory
      run: make clean
